# -*- coding: utf-8 -*-
# Copyright 2023 Ant Group CO., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

from knext.common.schema_helper import SPGTypeHelper, PropertyHelper


class SupplyChain:
    
    class Company(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        fundTrans6MonthIn = PropertyHelper("fundTrans6MonthIn")
        cashflowDiff3Month = PropertyHelper("cashflowDiff3Month")
        cashflowDiff6Month = PropertyHelper("cashflowDiff6Month")
        fundTrans1MonthIn = PropertyHelper("fundTrans1MonthIn")
        fundTrans6Month = PropertyHelper("fundTrans6Month")
        product = PropertyHelper("product")
        fundTrans3Month = PropertyHelper("fundTrans3Month")
        cashflowDiff1Month = PropertyHelper("cashflowDiff1Month")
        totalTransInAmt = PropertyHelper("totalTransInAmt")
        fundTrans3MonthIn = PropertyHelper("fundTrans3MonthIn")
        fundTrans1Month = PropertyHelper("fundTrans1Month")
    
    class CompanyEvent(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        eventTime = PropertyHelper("eventTime")
        trend = PropertyHelper("trend")
        index = PropertyHelper("index")
        subject = PropertyHelper("subject")
        belongTo = PropertyHelper("belongTo")
        leadTo = PropertyHelper("leadTo")
    
    class Index(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    class Industry(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        alias = PropertyHelper("alias")
        stdId = PropertyHelper("stdId")
    
    class Person(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        age = PropertyHelper("age")
        legalRepresentative = PropertyHelper("legalRepresentative")
        certNo = PropertyHelper("certNo")
    
    class Product(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        belongToIndustry = PropertyHelper("belongToIndustry")
        belongTo = PropertyHelper("belongTo")
        hasSupplyChain = PropertyHelper("hasSupplyChain")
    
    class ProductChainEvent(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        eventTime = PropertyHelper("eventTime")
        trend = PropertyHelper("trend")
        subject = PropertyHelper("subject")
        belongTo = PropertyHelper("belongTo")
        index = PropertyHelper("index")
    
    class TaxOfCompanyEvent(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    class TaxOfProdEvent(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        alias = PropertyHelper("alias")
        stdId = PropertyHelper("stdId")
    
    class TaxOfProduct(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    class Trend(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        alias = PropertyHelper("alias")
        stdId = PropertyHelper("stdId")
    
    Company = Company("SupplyChain.Company")
    CompanyEvent = CompanyEvent("SupplyChain.CompanyEvent")
    Index = Index("SupplyChain.Index")
    Industry = Industry("SupplyChain.Industry")
    Person = Person("SupplyChain.Person")
    Product = Product("SupplyChain.Product")
    ProductChainEvent = ProductChainEvent("SupplyChain.ProductChainEvent")
    TaxOfCompanyEvent = TaxOfCompanyEvent("SupplyChain.TaxOfCompanyEvent")
    TaxOfProdEvent = TaxOfProdEvent("SupplyChain.TaxOfProdEvent")
    TaxOfProduct = TaxOfProduct("SupplyChain.TaxOfProduct")
    Trend = Trend("SupplyChain.Trend")
    